#pragma once

#define BASEEFFECT_MAJOR 1
#define BASEEFFECT_MINOR 1
#define BASEEFFECT_PATCH 0
#define BASEEFFECT_VERSION ((BASEEFFECT_MAJOR << (8 * 3)) + (BASEEFFECT_MINOR << (8 * 2)) + (BASEEFFECT_PATCH << (8 * 1)))

#define _BASEEFFECT_VERSION_STR_TEXT(text) #text
#define _BASEEFFECT_VERSION_STR(major, minor, patch) _BASEEFFECT_VERSION_STR_TEXT(major) "." _BASEEFFECT_VERSION_STR_TEXT(minor) "." _BASEEFFECT_VERSION_STR_TEXT(patch)
#define BASEEFFECT_VERSION_STR _BASEEFFECT_VERSION_STR(BASEEFFECT_MAJOR, BASEEFFECT_MINOR, BASEEFFECT_PATCH)
